# Assumes backend layers, JAR and dockerfile have been created, see README.md

services:
  reverse-proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
     - frontend
     - backend
  frontend:
    image: mtuomiko/citybikeapp-frontend
    build:
      context: . # frontend client code generation needs access to backend API spec file so using root context
      dockerfile: docker/Dockerfile.frontend
    pull_policy: build
    depends_on:
     - backend
  backend:
    image: mtuomiko/citybikeapp-backend
    build:
      context: ./citybikeapp-backend/
      dockerfile: Containerfile
    pull_policy: build
    environment:
      - DATABASE_CONNECTION_URL
      - DATABASE_CONNECTION_USERNAME
      - DATABASE_CONNECTION_PASSWORD
    depends_on:
     - db
    healthcheck:
      # wget is available from the eclipse-temurin alpine image, so using that
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 15s
      timeout: 5s
      start_period: 10s

  dataloader:
    image: mtuomiko/citybikeapp-backend
    environment:
      - SPRING_PROFILES_ACTIVE=default,dataloader
      - DATABASE_CONNECTION_URL
      - DATABASE_CONNECTION_USERNAME
      - DATABASE_CONNECTION_PASSWORD
    depends_on:
      backend:
        # Haven't seen real issues, but nicer to let only a single instance attempt to do flyway migration stuff.
        # So idea is that backend starts first, completes DB migration, and only afterwards dataloader instance runs.
        condition: service_healthy
      db:
        condition: service_started
    profiles:
     - dataloader
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_CONNECTION_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_CONNECTION_PASSWORD}
      POSTGRES_DB: citybikeapp
